#!/bin/bash
gcc --std=gnu99 -Wall -o dec_client ./dec_client_dir/*.c ./*.c
gcc --std=gnu99 -Wall -o dec_server ./dec_server_dir/*.c ./*.c
gcc --std=gnu99 -Wall -o enc_client ./enc_client_dir/*.c ./*.c
gcc --std=gnu99 -Wall -o enc_server ./enc_server_dir/*.c ./*.c
gcc --std=gnu99 -Wall -o keygen ./keygen_dir/*.c
